# Generated by Django 4.0.2 on 2022-02-25 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='اسم دسته')),
                ('photo', models.ImageField(upload_to='products_category', verbose_name='عکس دسته')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای کامنت')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال کامنت')),
                ('grade', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('stars', models.CharField(default=0, max_length=5)),
                ('stars_left', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای کامنت')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پست کامنت')),
                ('grade', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز کامنت')),
                ('stars', models.CharField(default=0, max_length=5)),
                ('stars_left', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='contact_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='اسم دسته')),
                ('photo', models.ImageField(upload_to='products_category', verbose_name='عکس سر دسته')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تیکت')),
                ('question', models.TextField(verbose_name='سوال شما')),
                ('answer', models.TextField(blank=True)),
                ('is_answerd', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
