# Generated by Django 4.0.2 on 2022-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='bank_account',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myshop',
            name='about',
            field=models.TextField(blank=True, verbose_name='درباره ی فروشگاه'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='description_look',
            field=models.TextField(blank=True, verbose_name='توضیحات پوستر'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='image_banner1',
            field=models.ImageField(blank=True, upload_to='shops.banner', verbose_name='عکس بنر اول'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='image_banner2',
            field=models.ImageField(blank=True, upload_to='shops.banner', verbose_name='عکس بنر دوم'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='image_banner3',
            field=models.ImageField(blank=True, upload_to='shops.banner', verbose_name='عکس بنر سوم'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='image_look',
            field=models.ImageField(blank=True, upload_to='shops.look', verbose_name='عکس پوستر'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='seller_info',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='title_look',
            field=models.CharField(blank=True, max_length=50, verbose_name='عنوان پوستر'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='why_us1',
            field=models.CharField(blank=True, max_length=50, verbose_name='عنوان اول چرا ما'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='why_us2',
            field=models.CharField(blank=True, max_length=50, verbose_name='عنوان دوم چرا ما'),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='why_us3',
            field=models.CharField(blank=True, max_length=50, verbose_name='عنوان سوم چرا ما'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
