# Generated by Django 4.0.2 on 2022-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_myshop_bank_account_alter_myshop_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshop',
            name='image_head1',
            field=models.ImageField(default='shops.head/1713248.jpg', upload_to='shops.head', verbose_name='عکس تیتر اول'),
        ),
    ]
